package com.mibanco.generarpdfhistorialcrediticiodetallado.us.util;

import jakarta.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class Util {

    public static String obtenerDescripcion(String codigo) {
        switch (codigo) {
            case "CCB": return "CUENTA CORRIENTE BANCARIA";
            case "CCD": return "CUENTA CORRIENTE DIGITAL";
            case "TDC": return "TARJETAS DE CRÉDITO  ";
            case "TDD": return "TARJETAS DE CRÉDITO DIGITAL";
            case "CBR": return "CARTERA BANCARIA ROTATIVA  ";
            case "CRD": return "CARTERA BANCARIA ROTATIVA DIGITAL";
            case "CAU": return "CARTERA AUTOMOTRIZ  ";
            case "CAM": return "MANTENIMIENTO  Y  REPARACIÓN  DE  VEHÍCULOS AUTOMOTORES";
            case "CAP": return "COMERCIO DE PARTES, PIEZAS (AUTOPARTES) Y ACCESORIOS (LUJOS) PARA VEHÍCULOS AUTOMOTORES";
            case "CMO": return "COMERCIO DE MOTOCICLETAS Y DE SUS PARTES, PIEZAS Y ACCESORIOS";
            case "CAL": return "COMPAÑIAS LLANTERAS";
            case "CAB": return "CARTERA BANCARIA  ";
            case "CBD": return "CARTERA BANCARIA DIGITAL";
            case "FIT": return "FINTECH";
            case "CBC": return "COLECTIVA";
            case "CBF": return "FIDUCIARIA";
            case "CLV": return "LINEA VERDE - SOSTENIBLE";
            case "CFI": return "FIDEICOMISO";
            case "CME": return "FINANCIACION MONEDA EXTRANJERA";
            case "CBO": return "OFICIAL";
            case "CAC": return "CART. COOP DE AHORRO Y CREDITO  ";
            case "COF": return "CARTERA CORPORAC. FINANCIERAS  ";
            case "CFM": return "FOMENTO MUNICIPAL";
            case "CFD": return "FOMENTO DEPARTAMENTAL";
            case "CFF": return "FINAGRO";
            case "CFE": return "CARTERA FONDOS DE EMPLEADOS  ";
            case "CVE": return "CARTERA VESTUARIO  ";
            case "CLB": return "CARTERA EDITORIAL  ";
            case "COC": return "CARTERA OTROS CREDITOS  ";
            case "CPE": return "PAGO EN ESPECIE";
            case "CPG": return "PIGNORACION";
            case "CVB": return "VENTA DE BIENES";
            case "CMS": return "CORREO Y SERVICIOS DE MENSAJERÍA";
            case "CSM": return "SERVICIOS MEDICOS  ";
            case "CVT": return "ACTIVIDADES VETERINARIAS";
            case "CAA": return "ALQUILER Y ARRENDAMIENTO DE OTROS TIPOS DE MAQUINARIA, EQUIPO Y BIENES TANGIBLES N.C.P.";
            case "CFU": return "SERVICIOS FÚNEBRES Y ACTIVIDADES RELACIONADAS";
            case "CAS": return "ASESORIAS  ";
            case "CTU": return "CARTERA TURISMO  ";
            case "CTR": return "RECREACIÓN";
            case "CAV": return "CARTERA AHORRO Y VIVIENDA  ";
            case "CVN": return "VIVIENDA NO VIS";
            case "CVP": return "VIVIENDA PRIORITARIA";
            case "CVV": return "VIVIENDA VIS";
            case "CCL": return "CARTERA COMPANIAS DE LEASING  ";
            case "LNV": return "LEASING HABITACIONAL NO  VIS";
            case "LHV": return "LEASING HABITACIONAL VIS";
            case "LAP": return "LEASING APALANCADO";
            case "LFI": return "LEASING FINANCIERO";
            case "LIN": return "LEASING INMOBILIARIO";
            case "LVE": return "LEASING VEHICULAR";
            case "LOP": return "LEASING OPERATIVO";
            case "LOT": return "LEASING OTROS";
            case "LBK": return "LEASE BACK";
            case "CCC": return "CARTERA CRED. DE CONSTRUCCION  ";
            case "CFR": return "CARTERA FINCA RAIZ  ";
            case "CFA": return "ARRENDAMIENTO";
            case "CIN": return "INVERSION NO VIS";
            case "CIV": return "INVERSION VIS";
            case "EST": return "ESTATAL  ";
            case "CCF": return "CARTERA C/IAS. FINANC. CIAL.  ";
            case "CRE": return "REDESCUENTO";
            case "CFT": return "FACTORING";
            case "COR": return "ORDINARIO";
            case "CCM": return "CARTERA MOTOS";
            case "CMD": return "CARTERA MOTOR DIGITAL";
            case "CVH": return "CARTERA VEHICULO";
            case "CVD": return "CARTERA VEHICULO DIGITAL";
            case "CMU": return "CARTERA MUEBLES  ";
            case "CCS": return "CARTERA COMPANIAS DE SEGUROS  ";
            case "SAC": return "SEGUROS ACCIDENTES";
            case "SGE": return "SEGUROS GENERALES";
            case "SHO": return "SEGUROS HOGAR";
            case "SVE": return "SEGUROS VEHICULO";
            case "SVI": return "SEGUROS VIDA";
            case "CBM": return "CREDITOS DE BAJO MONTO  ";
            case "CEL": return "CARTERA ELECTRODOMESTICOS  ";
            case "CTC": return "CARTERA TELEFONIA CELULAR  ";
            case "CSB": return "SPLIT BILLING - CORPORATIVA";
            case "CDC": return "CARTERA DE COMUNICACIONES  ";
            case "CCH": return "HOGARES (TV, BANDA ANCHA, FIJO)";
            case "CCO": return "CORPORATIVO (TV, BANDA ANCHA, FIJO)";
            case "CPY": return "PYME (TV, BANDA ANCHA, FIJO)";
            case "DIC": return "DEPARTAMENTO INFORM. COMERCIAL  ";
            case "CDB": return "CARTERA COMISIONISTAS DE BOLSA  ";
            case "CSP": return "CARTERA SERVICIOS PUBLICOS  ";
            case "CSU": return "SERVICIO AGUA";
            case "CSL": return "SERVICIO LUZ";
            case "CSG": return "SERVICIO GAS";
            case "AGR": return "CARTERA AGROINDUSTRIA";
            case "RUR": return "RURAL";
            case "ALI": return "CARTERA DE ALIMENTOS  ";
            case "CMZ": return "CARTERA COMERCIALIZADORAS  ";
            case "CSA": return "CARTERA CAJAS COMPENS. Y SALUD  ";
            case "COM": return "CARTERA DE EQUIPOS";
            case "FER": return "CARTERA FERRETERIAS  ";
            case "FUN": return "CARTERA FUNDACIONES  ";
            case "GRM": return "CARTERA GREMIOS  ";
            case "IND": return "CARTERA INDUSTRIAL  ";
            case "LAB": return "CARTERA LABORATORIOS  ";
            case "CDI": return "VENTA DIRECTA";
            case "LBZ": return "CARTERA LIBRANZA  ";
            case "LBD": return "CARTERA LIBRANZA DIGITAL";
            case "LBE": return "LIBRANZA EMPLEADOS";
            case "LBP": return "LIBRANZA PENSIONADOS";
            case "LBR": return "LIBRANZA ROTATIVA";
            case "LBC": return "LIBRANZA COMPRA CARTERA";
            case "SEG": return "CARTERA SEGURIDAD  ";
            case "TRT": return "CARTERA TRANSPORTE";
            case "EDU": return "CARTERA EDUCACION";
            case "SFI": return "SERVICIOS FINANCIEROS";
            case "SCC": return "CASAS DE COBRANZA";
            case "CON": return "CREDITOS DE CONSUMO";
            case "APD": return "ALMACEN POR DEPARTAMENTOS";
            case "SBG": return "CARTERA SOBREGIRO";
            case "MCR": return "CARTERA MICROCREDITO";
            case "AHO": return "CUENTAS DE AHORRO BANCARIA";
            case "AHD": return "CUENTAS DE AHORRO BANCARIA DIGITAL";
            case "CDT": return "CDT";
            default: return null;
        }
    }
}
